[package]
name = "local-render-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digital-garden-visitor-counter = { path = "../" }
minifb = "0.25.0"
